# Generated by Django 3.2.4 on 2021-06-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interest_rate', models.IntegerField(default=10)),
                ('amount', models.BigIntegerField(default=1000)),
                ('emi', models.IntegerField(default=0)),
                ('tenure', models.IntegerField(default=12)),
                ('status', models.IntegerField(choices=[('Approved', 1), ('Rejected', 2), ('New', 3)], default=3)),
                ('extra_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=20)),
                ('prodcut_interest', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
