# Generated by Django 3.2.4 on 2021-06-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='extra_details',
            field=models.JSONField(default={}),
        ),
    ]
