# Generated by Django 3.2.4 on 2021-06-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='extra_details',
            field=models.JSONField(default=dict),
        ),
    ]
