# Generated by Django 3.2.4 on 2021-06-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('New', 'New')], max_length=20),
        ),
    ]
